[package]
name = "vex-generator"
version = "0.1.0"
edition = "2021"

[dependencies.vex]
path = "../vex"

[dependencies.nom]
version = "7"

[dependencies.serde]
version = "^1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"
